/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jboss.jbossset.bugclerk;

import org.jboss.pull.shared.connectors.bugzilla.Bug;
import org.jboss.pull.shared.connectors.bugzilla.Comment;
import org.jboss.pull.shared.connectors.common.Flag;

import  org.jboss.jbossset.bugclerk.Violation;

global java.util.List list

rule "ComponentUpgradeMissingFixList"
    dialect "mvel"
    when
      $candidate : Candidate( bug.type == "Component Upgrade", bug.DependsOn.size == 0, filtered == false);
    then
	  insert( new Violation($candidate.bug,drools.getRule().getName(),  "Component Upgrade BZ does not have any fixes it depends on !"));
		
end