/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2015, Red Hat, Inc., and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

package org.jboss.jbossset.bugclerk;

import org.jboss.pull.shared.connectors.bugzilla.Bug;


rule "IgnoreDocFeatureBZ"
  salience 100
  dialect "mvel"
  when
    $candidate : Candidate( bug.summary.contains("[Doc Feature]"), filtered == false);
  then
    //System.out.println($candidate.bug.id + " filtered by " + drools.getRule().getName());
    modify ( $candidate ) {
      candidate = false,
      filtered = true
    };
end

rule "IgnoreDocumentationTypeBZ"
  salience 100
  dialect "mvel"
  when
    $candidate : Candidate( bug.type.contains("Documentation"), filtered == false);
  then
    //System.out.println($candidate.bug.id + " filtered by " + drools.getRule().getName());
    modify ( $candidate ) {
      candidate = false,
      filtered = true
    };
end

rule "IgnoreClosedBZ"
  salience 100
  dialect "mvel"
  when
    $candidate : Candidate( bug.status == "CLOSED", filtered == false);
  then
    //System.out.println($candidate.bug.id + " filtered by " + drools.getRule().getName());
    modify ( $candidate ) {
      candidate = false,
      filtered = true
    };
end

rule "IgnoreDuplicateBZ"
  salience 100
  dialect "mvel"
  when
    $candidate : Candidate( bug.resolution == "DUPLICATE", filtered == false);
  then
    //System.out.println($candidate.bug.id + " filtered by " + drools.getRule().getName());
    modify ( $candidate ) {
      candidate = false,
      filtered = true
    };
end


rule "IgnoreRpmsBZ"
  salience 100
  dialect "mvel"
  when
    $candidate : Candidate( bug.summary.contains("RPMs"), filtered == false);
  then
    //System.out.println($candidate.bug.id + " filtered by " + drools.getRule().getName());
    modify ( $candidate ) {
      candidate = false,
      filtered = true
     };
end

rule "SetIgnoreFlags"
  salience 100
  dialect "mvel"
  when
    $candidate : Candidate( comments.size() > 0, $comments : comments, filtered == false);
  Comment( text.contains("BugClerk#"), $comment : text ) from $comments;
  then
    //System.out.println(drools.getRule().getName() + ":" + $comment + "[" + $comment.getClass() + "]");
    $candidate.addRuleToIgnore($comment);
end
