/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2017, Red Hat, Inc., and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.jboss.jbossset.bugclerk;

import org.jboss.set.aphrodite.domain.User;
import org.jboss.set.aphrodite.domain.Issue;
import org.jboss.set.aphrodite.domain.IssuePriority;
import org.jboss.set.aphrodite.domain.Comment;
import org.jboss.set.aphrodite.domain.IssueStatus;
import org.jboss.set.aphrodite.domain.FlagStatus;
import org.jboss.set.aphrodite.issue.trackers.jira.JiraIssue;
import org.jboss.set.aphrodite.issue.trackers.jira.JiraChangelogGroup;

import java.util.Date;

import org.jboss.jbossset.bugclerk.Violation;
import org.jboss.jbossset.bugclerk.Severity;
import org.jboss.jbossset.bugclerk.utils.RulesHelper;

global java.util.List list

rule "FixVersionChangesDuringSprint"
  salience 0
  dialect "mvel"
  when
      $candidate : Candidate($jiraIssue: bug#JiraIssue,  filtered == false);
      $group : JiraChangelogGroup() from RulesHelper.getLastFixVersionChangeDuringSprint($jiraIssue);
      $sprint : String() from $jiraIssue.getSprintRelease();
      $author : User() from $group.getAuthor();
      eval(RulesHelper.isFixVersionChangeDoneByAllowedUser($author, $sprint) == false);
  then
    $candidate.addViolationOnce( new Violation("FixVersionChangesDuringSprint", "test violation", Severity.MAJOR) );
end
