package org.jboss.jbossset.bugclerk;

import org.jboss.set.aphrodite.domain.User;
import org.jboss.set.aphrodite.domain.Issue;
import org.jboss.set.aphrodite.domain.IssuePriority;
import org.jboss.set.aphrodite.domain.Comment;
import org.jboss.set.aphrodite.domain.IssueStatus;
import org.jboss.set.aphrodite.domain.FlagStatus;
import org.jboss.set.aphrodite.issue.trackers.jira.JiraIssue;
import org.jboss.set.aphrodite.issue.trackers.jira.JiraChangelogGroup;

import java.util.Date;

import org.jboss.jbossset.bugclerk.Violation;
import org.jboss.jbossset.bugclerk.Severity;
import org.jboss.jbossset.bugclerk.utils.RulesHelper;

global java.util.List list

rule "FixVersionChangesDuringSprint"
  salience 0
  dialect "mvel"
  when
      $candidate : Candidate($jiraIssue: bug#JiraIssue,  filtered == false);
      $group : JiraChangelogGroup() from RulesHelper.getLastFixVersionChangeDuringSprint($jiraIssue);
      $sprint : String() from $jiraIssue.getSprintRelease();
      $author : User() from $group.getAuthor();
      eval(RulesHelper.isFixVersionChangeDoneByAllowedUser($author, $sprint) == false);
  then
    $candidate.addViolationOnce( new Violation("FixVersionChangesDuringSprint", "test violation", Severity.MAJOR) );
end
