/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2015, Red Hat, Inc., and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

package org.jboss.jbossset.bugclerk;

import org.jboss.set.aphrodite.domain.Issue;
import org.jboss.set.aphrodite.domain.Comment;
import org.jboss.set.aphrodite.domain.IssueStatus;

import org.jboss.jbossset.bugclerk.Violation;

rule "ReleaseVersionMismatch"
  salience 0
  dialect "mvel"
  when
    // FIXME: enhance pattern matching on summary
    $candidate : Candidate( bug.release.version.isPresent == true, $release : bug.release.version.get(), $summary : bug.summary.get() , filtered == false);
    eval ( $summary.matches("^.*6\\.[0-9]\\.[0-9].*$"))  // only go further if summmary DOES contains a version number
    eval(  $summary.contains($release) == false); // violation only if summary does NOT contains the right version number
  then
    insert( new Violation($candidate,drools.getRule().getName(), "Release in title does not match actual release (" + $release  + "]:" + $summary) );
end
