/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2015, Red Hat, Inc., and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

package org.jboss.jbossset.bugclerk;

import org.jboss.pull.shared.connectors.bugzilla.Bug;
import org.jboss.pull.shared.connectors.bugzilla.Comment;
import org.jboss.pull.shared.connectors.common.Flag;

import  org.jboss.jbossset.bugclerk.Violation;

rule "TargetRelease"
    dialect "mvel"
    when
       $candidate : Candidate($summary: bug.summary, $flags : bug.flags , filtered == false);
      $numberOfReleasesFlag : Number() from accumulate(i: Flag(name.contains("jboss-eap"), status == Status.UNKNOWN || status == Status.POSITIVE ) from $flags , count(i) );
      eval( $numberOfReleasesFlag > 1 )
    then
      insert(
        new Violation(
          $candidate.bug, drools.getRule().getName(), "Invalid number of flag Release: " +
          $numberOfReleasesFlag + " - only is one should be set. Flags are: " +
          $candidate.getFlagNamesContaining("jboss-eap") + "."));
end
