/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2015, Red Hat, Inc., and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

package org.jboss.jbossset.bugclerk;

import org.jboss.set.aphrodite.domain.Issue;
import org.jboss.set.aphrodite.domain.Comment;
import org.jboss.set.aphrodite.domain.IssueStatus;
import org.jboss.set.aphrodite.domain.FlagStatus;

import org.jboss.jbossset.bugclerk.Violation;

import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

// Apparently can't type collections arguments in Drools function...
function int flagsWithPrefix(String prefix, Map stream) {
  Map<String, FlagStatus> matches = new HashMap<String, FlagStatus>(stream.size());
  for ( Entry<String, FlagStatus> entry : ((Map<String,FlagStatus>)stream).entrySet() )
      if ( entry.getKey().contains(prefix) )
          matches.put(entry.getKey(),entry.getValue());
  return matches.size();
}

rule "TargetRelease"
  salience 0
  dialect "mvel"
  when
    $candidate : Candidate(bug.streamStatus.size() > 0 , bug.getType().toString == "UPGRADE" , $streamStatus : bug.streamStatus , filtered == false);
    eval( flagsWithPrefix("jboss", $streamStatus) > 1);
  then
    insert(new Violation($candidate, drools.getRule().getName(), "More than one release is set for this Issue."));
end
